### ISSUE TITLE
스마트 캠퍼스 모델 - 학과 사이트

### ISSUE THREAD

**Issue by JOyagdol** [Auint/knowledge-management-framework-for-smart-city#10]
![Department_Site_model](https://github.com/Auint/knowledge-management-framework-for-smart-city/blob/Joyagdol_branch/diagrams/Department_Site_model.png?raw=true)
[관계]

교직원 - Manage → 학과 사이트

학생 ← Provide Info - 학과 사이트

[Node(Label)]

학과 사이트

[속성]

학과 사이트 url, 학과 공지(장학, 행사) 등

[Node(Label)]

교직원

[속성]

대학, 학부(과), 교직원_ID 등

[Node(Label)]

학생

[속성]

학번, 대학, 학부(과), 학적상태, 학년, 생년월일, 수업구분, 주소, 휴대폰, 메일, nodeID, Student_ID, Student_PW

**Comment by Auint** [comment]
좋습니다.
해당 사항을 LPG혹은 RDF와 같은 형식으로
계속 이어나가면 될 것 같습니다.
