### ISSUE TITLE
동아대 스마트 캠퍼스 모델 구성

### ISSUE THREAD

**Issue by JOyagdol** [Auint/knowledge-management-framework-for-smart-city#3]
> 동아대 학과 수강신청 가능한 강의 - [[수강신청 조회](http://sugang.donga.ac.kr/SUGANGLECTIME.aspx)](http://sugang.donga.ac.kr/SUGANGLECTIME.aspx)
> 
> 
> 사하 10 공공 데이터 - [[버스 API](https://www.data.go.kr/data/15092750/openapi.do)](https://www.data.go.kr/data/15092750/openapi.do)
> 
> 대학 식당 정보 - [[Campus Cafeteria](https://www.donga.ac.kr/gzSub_007005005.aspx)](https://www.donga.ac.kr/gzSub_007005005.aspx)
> 
> [공지사항](http://www.donga.ac.kr/gzSub_007001.aspx) & 학사공지 & 장학공지 - [공지사항](http://www.donga.ac.kr/gzSub_007001.aspx)
> 
> [동아대](https://www.donga.ac.kr/Default.aspx) 웹사이트 - [동아대](https://www.donga.ac.kr/Default.aspx) [[학사안내](http://intra.donga.ac.kr/)](http://intra.donga.ac.kr/) [[LMS](https://eclass.donga.ac.kr/)](https://eclass.donga.ac.kr/) [[한림생활관](http://hanlim.donga.ac.kr/)](http://hanlim.donga.ac.kr/)
>

데이터 자료를 수집하고 관계에 대해 새롭게 정립할 필요가 있음.

학생정보 서비스, 학사 일정, 도서관 열람실, 교내 지도, 동아리, 전화번호, 졸업사정 등 데이터는 모델 구성에 적합한지 생각해 봐야함

**Comment by Auint** [comment]
잘하셨습니다.

모델 구성에 앞서서 다른 모델을 참고하여 장단점을 파악하여 진행하는 것이 좋습니다.
또한 해당 내용이 왜 필요한지 어떠한 부분과 연관성이 있는지에 대해 더 표기하면 좋겠습니다.

**Comment by JOyagdol** [comment]
감사합니다. 모델 구축 시 참고하여 필요성을 제시하는 방향으로 하겠습니다.

모델 구성에 앞서 다른 모델을 참고하여 장단점을 파악하는 것이 좋다고 하셨는데,
스마트 캠퍼스 모델은 없는 걸로 알고 있는데, 어떤 모델을 참고하라는 건지 궁금합니다.

**Comment by Auint** [comment]
스마트 캠퍼스 모델은 현재로써는 거의 논의되지 않았습니다.

다만 캠퍼스에서 일어나는 일이 어떤 형식으로 나타내는지는 다른 모델(프로세스, 프로그램)들을 참고하면 좋다는 것입니다.

예시로 학교에서 공식적으로 하는 앱이 아닌 this-is나 타 학교에서 학생들이 지원하는 부분 혹은 학교에서 지원하는 것들을 모아서 다른 참고할 만한 것들을 사용하면 좋습니다.
