### ISSUE TITLE
스마트 캠퍼스 모델 - 교과 강의

### ISSUE THREAD

**Issue by JOyagdol** [Auint/knowledge-management-framework-for-smart-city#4]
[관계]

학생 ← learn - 교과명

교수 - study → 교과명

[Node(Label)] 

교과명

[속성] 

수강학과, 이수구분, 학년, 학점, 담당교수, 강의시간, 강의실, 수업계획서url, 학년도-학기, 과목번호, 분반, 교과과정 정보, nodeID

**Comment by Auint** [comment]
관계와 속성을 잘 나타내었습니다.

다만 이러한 부분을 다이어그램 형식으로 전환하여 표기하는 것이 모델 부분에는 중요합니다.

**Comment by Auint** [comment]
추가로 하나의 주제로 issue를 진행한다면 새로운 issue를 파서 진행하는 것보다 해당 issue밑으로 진행하는 것이 좋습니다.

**Comment by JOyagdol** [comment]
넵 조언 해주셔서 감사합니다
참고하여 현재 레파지토리를 검토해보고 수정하도록 하겠습니다!

Get Android용 Outlook<https://aka.ms/AAb9ysg> 다운로드
________________________________
