### ISSUE TITLE
스마트 캠퍼스 모델 - 교과강의 추가

### ISSUE THREAD

**Issue by JOyagdol** [Auint/knowledge-management-framework-for-smart-city#5]
[Node(Label)]

학생

[속성]

학번, 대학, 학부(과), 학적상태, 학년, 생년월일, 수업구분, 주소, 휴대폰, 메일, nodeID

[Node(Label)]

교수

[속성]

대학, 학부(과), ... 

[+] 한 학기 마다 데이터 파싱을 통해 업데이트 필요

[+] [[수업계획서url 파싱](https://student.donga.ac.kr/Univ/SUE/SSUE0070.aspx?m=2)](https://student.donga.ac.kr/Univ/SUE/SSUE0070.aspx?m=2)

[+] [[교과과정조회](https://student.donga.ac.kr/Univ/SUE/SSUE0010.aspx?m=2)](https://student.donga.ac.kr/Univ/SUE/SSUE0010.aspx?m=2)

학생과 교수의 데이터 정보를 추가로 구성해야함

**Comment by Auint** [comment]
#4 
부분을 참고하시면 되겠습니다.
