### ISSUE TITLE
스마트 캠퍼스 모델 - 버스

### ISSUE THREAD

**Issue by JOyagdol** [Auint/knowledge-management-framework-for-smart-city#6]
사하 10 ([url](http://apis.data.go.kr/6260000/BusanBIMS/busInfoByRouteId?lineid=5291010000&serviceKey=3BkJ5XH7nvj1BsbJOiTm5bpntxuDiaEejcTvIxpqvDuF%2BibUVumXCClzCyL15F%2BmZT8cBc5Tryw6slexyzYrVQ%3D%3D))

[관계]

버스 정류장 - get on → 버스

버스 정류장 ← get off - 버스 

[Node(Label)]

버스 (carno)

[속성]

현재 버스 위치(정류장), 다음 정류장까지 걸리는 시간, 배차 시간, 노선 번호, 빈 좌석 수,nodeID

[Node(Label)]

버스 정류장

[속성]

도착 버스 시간 정보, nodeID

[+] 벡터를 이용해 버스 인원 체크

**Comment by Auint** [comment]
#4 
마찬가지로 다이어그램 형식으로 표기하고
데이터를 점차 증가시키면 좋을 것 같습니다.
(https://draw.io/) 과 비슷한  프로그램이나 방식을 사용하면 됩니다.
