### ISSUE TITLE
스마트 캠퍼스 모델 - 대학식당

### ISSUE THREAD

**Issue by JOyagdol** [Auint/knowledge-management-framework-for-smart-city#9]
![Cafeteria_model](https://github.com/Auint/knowledge-management-framework-for-smart-city/blob/main/diagrams/Uni_Cafeteria_model.png?raw=true)

[관계]

사용자 - eat → Day_Menu

사용자 ← provide info - Day_Menu

[Node(Labels)]

Day_Menu

[속성]

가격, 메뉴 재고 유무, 구분(ex_조식, 중식, 석식 / 정식, 일품 양분식 등), 날짜, 대학 식당 이름

[Node(Labels)]

사용자

[속성]

사용자 데이터(ex_교수 정보, 학생 정보), 당일 대학 식당 이용 데이터

[+] 대학교 캠퍼스 식당 키오스크와 네트워크 통신

[+] 조회(메뉴 재고 유무, 당일 메뉴 정보)

**Comment by Auint** [comment]
수고하셨습니다.
